github.com:
    users:
        backhauler1:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: backhauler1
